(function(){"use strict";const h=`Bạn là trợ lý phân tích hình ảnh. User gửi ảnh gốc và ảnh có annotation (khoanh tròn, mũi tên, ghi chú). Hãy đọc annotation và phản hồi.

QUY TẮC BẮT BUỘC:
- Luôn trả lời bằng tiếng Việt
- KHÔNG mở đầu kiểu "Dựa trên hình ảnh...", "Tôi thấy rằng...", "Theo annotation...". Vào thẳng nội dung
- KHÔNG dùng format đánh số với tiêu đề rồi xuống dòng giải thích. KHÔNG viết kiểu:
  1. Tiêu đề:
     - Giải thích
- Thay vào đó viết liền mạch, tự nhiên, gộp ý liên quan thành câu đọc được. Ví dụ: "Thu hẹp mắt lại cho sắc hơn. Thêm lông mày nhíu xuống giữa để tạo vẻ đe dọa. Đổi miệng thành nhăn hoặc gầm gừ."
- Mỗi ý là một câu ngắn gọn, nối tiếp nhau. Có thể xuống dòng giữa các nhóm ý khác nhau
- Nếu user muốn sửa ảnh AI, viết prompt tiếng Việt mà user có thể copy-paste luôn
- Cụ thể: nói "nút xanh góc phải" thay vì "phần tử đó"
- Ngắn gọn, thực tế, không rào trước đón sau`;async function c(){return new Promise(t=>{chrome.storage.local.get("apiKey",n=>{t(n.apiKey||null)})})}async function s(t){const n=await c();if(!n)throw new Error("API key not configured. Please set it in the extension settings.");const a=[{role:"system",content:h},{role:"user",content:[{type:"image_url",image_url:{url:`data:image/jpeg;base64,${t.originalImage}`,detail:"high"}},{type:"image_url",image_url:{url:`data:image/png;base64,${t.annotatedImage}`,detail:"high"}},{type:"text",text:t.prompt}]}],e=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${n}`},body:JSON.stringify({model:"gpt-4o",max_tokens:4096,messages:a})});if(!e.ok){const i=await e.json();throw new Error(`API error: ${i.error?.message||e.statusText}`)}return(await e.json()).choices?.[0]?.message?.content||"No response"}chrome.runtime.onInstalled.addListener(()=>{chrome.contextMenus.create({id:"annotate-image",title:"Edit with AI Annotation",contexts:["image"]})}),chrome.contextMenus.onClicked.addListener(async(t,n)=>{if(!(t.menuItemId!=="annotate-image"||!t.srcUrl)){await chrome.sidePanel.open({tabId:n.id}),await chrome.storage.session.set({pendingImage:{srcUrl:t.srcUrl,pageUrl:t.pageUrl,pageTitle:n?.title,timestamp:Date.now()}});try{await chrome.runtime.sendMessage({type:"IMAGE_FROM_CONTEXT_MENU",payload:{srcUrl:t.srcUrl,pageUrl:t.pageUrl,pageTitle:n?.title}})}catch{}}}),chrome.action.onClicked.addListener(async t=>{await chrome.sidePanel.open({tabId:t.id})}),chrome.runtime.onMessage.addListener((t,n,a)=>{if(t.type==="CAPTURE_TAB")return chrome.tabs.captureVisibleTab(null,{format:"jpeg",quality:85},e=>{chrome.runtime.sendMessage({type:"IMAGE_CAPTURED",dataUrl:e})}),!0;if(t.type==="FETCH_IMAGE"){const e=t.payload.url;return fetch(e).then(async r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);const i=await r.blob(),g=await i.arrayBuffer(),l=new Uint8Array(g);let o="";l.forEach(m=>o+=String.fromCharCode(m)),a({base64:btoa(o),mimeType:i.type||"image/jpeg"})}).catch(r=>{a({error:r.message})}),!0}if(t.type==="SEND_TO_AI")return s(t.payload).then(e=>{a({type:"AI_RESPONSE",payload:{text:e}})}).catch(e=>{a({type:"AI_ERROR",payload:{error:e.message}})}),!0})})();
